[package]
name = "lr3_cond"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
genetic_algorithm = { path = "../genetic_algorithm" }
clap = { version = "3.0.14", features = ["derive"] }
